//
//  UIColor+YIColors.swift
//
//  Generated by Zeplin on 3/29/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
    class func yiGrapeColor() -> UIColor {
        return UIColor(red: 108.0 / 255.0, green: 42.0 / 255.0, blue: 88.0 / 255.0, alpha: 1.0)
    }
    
    class func yiDarkishPinkColor() -> UIColor {
        return UIColor(red: 232.0 / 255.0, green: 48.0 / 255.0, blue: 138.0 / 255.0, alpha: 1.0)
    }
    
    class func yiMangoColor() -> UIColor {
        return UIColor(red: 249.0 / 255.0, green: 178.0 / 255.0, blue: 51.0 / 255.0, alpha: 1.0)
    }
    
    class func yiWhiteColor() -> UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 1.0)
    }
    
    class func yiWhiteTwoColor() -> UIColor {
        return UIColor(white: 243.0 / 255.0, alpha: 1.0)
    }
    
    class func yiBlackColor() -> UIColor {
        return UIColor(white: 47.0 / 255.0, alpha: 1.0)
    }
    
    class func yiMidBlueColor() -> UIColor {
        return UIColor(red: 29.0 / 255.0, green: 113.0 / 255.0, blue: 184.0 / 255.0, alpha: 1.0)
    }
    
    class func yiGrapeTwoColor() -> UIColor {
        return UIColor(red: 88.0 / 255.0, green: 37.0 / 255.0, blue: 77.0 / 255.0, alpha: 1.0)
    }
    
    class func yiPeaColor() -> UIColor {
        return UIColor(red: 149.0 / 255.0, green: 193.0 / 255.0, blue: 31.0 / 255.0, alpha: 1.0)
    }
    
    class func yiSicklyGreenColor() -> UIColor {
        return UIColor(red: 138.0 / 255.0, green: 181.0 / 255.0, blue: 24.0 / 255.0, alpha: 1.0)
    }
    
    class func yiSicklyGreenTwoColor() -> UIColor {
        return UIColor(red: 140.0 / 255.0, green: 184.0 / 255.0, blue: 24.0 / 255.0, alpha: 1.0)
    }
    
    class func yiWhiteThreeColor() -> UIColor {
        return UIColor(white: 231.0 / 255.0, alpha: 1.0)
    }
    
    class func yiBgGradientOneColor() -> UIColor {
        return UIColor(white: 252.0 / 255.0, alpha: 1.0)
    }
    
    class func yiBgGradientTwoColor() -> UIColor {
        return UIColor(white: 247.0 / 255.0, alpha: 1.0)
    }
    
    class func yiGraphBarOneColor() -> UIColor {
        return UIColor(white: 243.0 / 255.0, alpha: 1.0)
    }
    
    class func yiGraphBarTwoColor() -> UIColor {
        return UIColor(white: 213.0 / 255.0, alpha: 1.0)
    }
    
    class func yiMango95Color() -> UIColor {
        return UIColor(red: 249.0 / 255.0, green: 179.0 / 255.0, blue: 53.0 / 255.0, alpha: 0.95)
    }
}
