# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Yona' do
   
pod 'R.swift'
#pod 'HockeySDK'
pod 'Google/Analytics'
pod 'Kingfisher', '~> 2.4'
end
